JEN-957 enable cron for trunk job
Percona-Lab/ps-build pull request #175
Opened 2019-04-02 19:40 UTC by hors

2019-04-03 05:57 UTC, laurynas-biveinis commented
What does this schedule say?

2019-04-03 06:31 UTC, laurynas-biveinis requested changes
Friday's run is too late for its week. Let's move the schedule one day back (Sunday to Thursday 11PM), because then we have fresh results on Monday

2019-04-03 07:02 UTC, hors commented
> Friday's run is too late for its week. Let's move the schedule one day back (Sunday to Thursday 11PM), because then we have fresh results on Monday

ok, done

2019-04-04 06:33 UTC, delgod approved these changes

2019-04-04 06:34 UTC, merged