JEN-1084 change the value for --testcase-timeout option
Percona-Lab/ps-build pull request #194
Opened 2019-04-25 11:41 UTC by hors

* in case of 'only-big-test' we need to use bigger value for
      '--testcase-timeout' option to avoid timeout issue in
      tests

2019-04-26 05:31 UTC, laurynas-biveinis requested changes

2019-04-26 05:31 UTC, laurynas-biveinis commented on local/test-binary
> +if [[ "${MTR_ARGS}" == *"--only-big-test"* ]]; then
--only-big-test or --big-test

2019-04-26 07:43 UTC, hors commented on local/test-binary
> +if [[ "${MTR_ARGS}" == *"--only-big-test"* ]]; then
ok, fixed

2019-05-03 06:33 UTC, laurynas-biveinis approved these changes

2019-05-03 07:12 UTC, merged