PS-7390: Remove --non-parallel-test from default MTR args
Percona-Lab/ps-build pull request #275
Opened 2020-10-23 13:24 UTC by Sudokamikaze

If we want to have a backward compatibility(in order to run older than 8.0.22) I'd add a version check from `mysqld --version`

2020-10-23 15:01 UTC, EvgeniyPatlan requested changes
where is link to the jenkins?

2020-10-24 17:06 UTC, Sudokamikaze commented
> where is link to the jenkins?

Hi @EvgeniyPatlan 
I've updated dsc, here's the link https://ps3.cd.percona.com/job/percona-server-8.0-pipeline/3624/

2020-10-26 10:57 UTC, kamil-holubicki approved these changes
lgtm

>If we want to have a backward compatibility(in order to run older than 8.0.22) I'd add a version check from mysqld --version

In my opinion we don't need it in Jenkinsfile (it will make pipeline configuration more complicated). This solution is still backward compatible as the flag can be set via MTR_ARGS

2020-10-26 11:47 UTC, EvgeniyPatlan approved these changes

2020-10-26 11:47 UTC, percona-ysorokin approved these changes
LGTM

2020-10-26 11:49 UTC, merged