WIP: PS-7382: Implement HashiCorp Vault for Keyring Vault tests
Percona-Lab/ps-build pull request #284
Opened 2020-11-04 10:59 UTC by Sudokamikaze

Builds: TBA

2020-11-05 10:54 UTC, EvgeniyPatlan requested changes

2020-11-05 10:54 UTC, EvgeniyPatlan commented on docker/install-deps
> +useradd -m --system --home /etc/vault.d-1.5.4-prod --shell /bin/false vault-1.5.4-prod
```suggestion
for VER in 0.9.6 1.5.4; do
useradd -m --system --home /etc/vault.d-$VER-dev --shell /bin/false vault-$VER-dev
useradd -m --system --home /etc/vault.d-$VER-prod --shell /bin/false vault-$VER-prod
done
```

2020-11-05 14:13 UTC, Sudokamikaze commented on docker/install-deps
> +useradd -m --system --home /etc/vault.d-1.5.4-prod --shell /bin/false vault-1.5.4-prod
Done :)

2020-12-31 10:16 UTC, Sudokamikaze commented
Closing, as it was reworked and made for 5.7
8.0 version will be implemented sooner

2020-12-31 10:16 UTC, closed without merging