PS-7382: [8.0] Add dependencies for Hashicorp Vault MTR tests
Percona-Lab/ps-build pull request #289
Opened 2020-11-16 08:27 UTC by Sudokamikaze

First part of implementation, Yura started working on 5.7, but `ps-build` image for 5.7 uses the one from 8.0 branch

Next PR will be for 5.7: MTR tests and all required changes to run build with Vault

Latest build with changes which used the `ps-build` with these changes: https://ps57.cd.percona.com/job/percona-server-5.7-pipeline-ps-7382/11/

2020-11-18 13:50 UTC, EvgeniyPatlan approved these changes

2020-11-18 19:40 UTC, percona-ysorokin requested changes

2020-11-18 19:40 UTC, percona-ysorokin commented on docker/install-deps
> +wget_loop "vault_0.9.6.zip" "https://releases.hashicorp.com/vault/0.9.6/vault_0.9.6_linux_amd64.zip"
Please, define 0.9.6 and 1.5.4 as LATEST_V1_VERSION and LATEST_V2_VERSION (or similar) environment variables correspondingly and change all other occurrences with these vars.
1.5.4 will definitely be changed as Hashicorp Vault evolves and it would be nice to change its version in one place.

2020-11-19 15:16 UTC, Sudokamikaze commented on docker/install-deps
> +wget_loop "vault_0.9.6.zip" "https://releases.hashicorp.com/vault/0.9.6/vault_0.9.6_linux_amd64.zip"
Fixed in 
8b15c12

2020-11-19 15:26 UTC, percona-ysorokin approved these changes
LGTM

2020-11-19 15:43 UTC, merged