ENG-969: [PS8.0] Implement AWS ECR for our internal build images
Percona-Lab/ps-build pull request #308
Opened 2021-02-03 15:50 UTC by Sudokamikaze

Link to prepare job:
Link to test pipeline:

2021-02-04 06:46 UTC, delgod requested changes
`./jenkins/pipeline.groovy` and `./jenkins/pipeline-fb.groovy` must do `docker login` before run `run-build` and `run-test`.

reason: when docker image is downloaded using an AWS Account - traffic is free.
please see https://aws.amazon.com/ecr/pricing/

2021-02-04 06:46 UTC, delgod commented on jenkins/prepare-ps-build-docker.yml
> +                        git poll: true, branch: '8.0-ENG-969', url: 'https://github.com/Sudokamikaze/ps-build'
please rollback

2021-02-04 06:56 UTC, delgod requested changes

2021-02-04 06:56 UTC, delgod commented on jenkins/prepare-ps-build-docker.yml
> +                        docker login -u AWS -p \$ECR_TEMP_PASS public.ecr.aws/e7j3v3n0
more secure command (password not shown in the logs)

```
aws ecr-public get-login-password --region us-east-1 \
    | docker login --username AWS --password-stdin public.ecr.aws/e7j3v3n0
```

2021-02-11 11:56 UTC, EvgeniyPatlan approved these changes

2021-02-11 12:00 UTC, delgod approved these changes

2021-02-12 09:48 UTC, delgod approved these changes

2021-02-13 08:46 UTC, merged