WIP: PS-7749: Implement ZenFS testing based on Ubuntu 21.04 for PS8.0 Param
Percona-Lab/ps-build pull request #337
Opened 2021-06-17 11:03 UTC by Sudokamikaze

Work in progress

2021-06-21 05:16 UTC, EvgeniyPatlan approved these changes

2021-07-30 11:00 UTC, percona-ysorokin requested changes

2021-07-30 11:00 UTC, percona-ysorokin commented on local/build-binary
> +    mkdir ${WORKDIR}/rocksdb-root ${WORKDIR}/rocksdb-build
```suggestion
    mkdir ${INSTALL_ROOT} ${BUILD_ROOT}
```

2021-07-30 11:00 UTC, percona-ysorokin commented on local/build-binary
> +    rm -rf ${INSTALL_ROOT} ${BUILD_ROOT}
Just in case, please also remove `zenfs` plugin symlink created earlier and `${SOURCEDIR}/storage/rocksdb/rocksdb/plugin/zenfs/util/zenfs` binary from the source tree.

2021-07-30 11:00 UTC, percona-ysorokin commented on local/nullblk-zoned
> +        done
Probably checking for free nullb device logic is no longer needed as we are specifying device id explicitly now.

2021-07-30 11:00 UTC, percona-ysorokin commented on local/test-binary
> +        sudo zenfs mkfs --zbd nullb1 --aux_path $AUX_PATH_1
These two must not be run under `sudo` as we already gave rw permissions to `/dev/nullbX`

2021-07-30 11:00 UTC, percona-ysorokin commented on local/test-binary
> +            sudo zbd report /dev/nullb$nulldevice
All those commands without `sudo` as well

2021-07-30 11:00 UTC, percona-ysorokin commented on local/test-binary
> +        sudo chmod -R 770 $AUX_PATH_0 $AUX_PATH_1
Probably not needed as `zenfs mkfs` should also be run under 27:27 user

2021-08-10 14:38 UTC, Sudokamikaze commented on local/test-binary
> +        sudo chmod -R 770 $AUX_PATH_0 $AUX_PATH_1
It's needed to ensure that AUX_PATH directory contains correct permissions before invoking mkfs of zenfs

2021-08-10 15:18 UTC, percona-ysorokin requested changes

2021-08-10 15:18 UTC, percona-ysorokin commented on docker/install-deps
> +    if [[ ${DIST} == "focal" ]]; then
Should we somehow differentiate between regular `focal` and `patched 5.11 kernel focal` here. The former does not need all those additional packages

2021-08-10 15:18 UTC, percona-ysorokin commented on docker/run-test
> +            sudo chmod 770 /dev/nullb$nulldevice
Why do we need +x permission here? Shouldn't it be `660`?

2021-08-10 15:18 UTC, percona-ysorokin commented on local/test-binary
> +            sudo zbd report /dev/nullb$nulldevice
Not addressed

2021-08-10 15:18 UTC, percona-ysorokin commented on local/test-binary
> +        sudo chmod -R 770 $AUX_PATH_0 $AUX_PATH_1
Both `$AUX_PATH_0` and  `$AUX_PATH_1` should have already been created earlier by `zenfs mkfs` invokations. Moreover, as they are invoked under non-privileged user, there is no need to change ownership/permissions here.

2021-08-24 10:43 UTC, percona-ysorokin approved these changes
LGTM

2021-08-25 08:20 UTC, merged