PS-8556 Jenkins MTR run should also allow to run tests requiring ps-p…
Percona-Lab/ps-build pull request #403
Opened 2023-11-28 06:57 UTC by surbhat1595

…rotocol

2023-11-29 11:14 UTC, inikep requested changes

2023-11-29 11:14 UTC, inikep commented on jenkins/param-parallel-mtr.yml
> +    name: percona-server-8.0-param-parallel-mtr-ps8556
I think we don't want to change job name. In all places it should stay `percona-server-8.0-param-parallel`.

2023-11-29 11:14 UTC, inikep commented on jenkins/param-parallel-mtr.yml
> +      - project: percona-server-8.0-pipeline-parallel-mtr-ps8556
In all 4 places it should stay `percona-server-8.0-pipeline-parallel`.

2023-11-29 11:14 UTC, inikep commented on local/test-binary-parallel-mtr
> +    MTR_ARGS_PS=${MTR_ARGS_PS//"--mem"/""}
Probably not required.

2023-11-29 11:14 UTC, inikep commented on local/test-binary-parallel-mtr
> +    # Requested in PS-7602
Please remove this and next lines.

2023-11-29 14:11 UTC, inikep commented on local/test-binary-parallel-mtr
> +    fi
This should be removed after https://github.com/Percona-Lab/ps-build/pull/401 was merged

2023-12-01 13:07 UTC, inikep requested changes
You didn't address my comments regarding to removing `-ps8556` from the pipeline/param name.
The rest looks good.

2023-12-01 13:23 UTC, inikep commented
Probably it will be good to rebase your branch to current `Percona-Lab:8.0` to solve conflicts.

2023-12-04 10:16 UTC, inikep approved these changes
LGTM

2023-12-04 15:05 UTC, percona-ysorokin approved these changes
LGTM

2023-12-05 05:09 UTC, merged