JEN-913 prevent wrong version run
Percona-Lab/ps-build pull request #57
Opened 2018-09-18 14:13 UTC by abychko

2018-09-19 06:14 UTC, laurynas-biveinis requested changes
For the highest version, which is 8.0 currently, only forbid building lower versions. If 8.1 or 9.0 comes along, we'd try building it with 8.0 jobs at first

2018-09-19 10:17 UTC, abychko commented
higher versions are allowed

2018-09-19 11:31 UTC, abychko commented
right version https://ps.cd.percona.com/view/5.5/job/test-percona-server-8.0-pipeline/11/
wrong version https://ps.cd.percona.com/view/5.5/job/test-percona-server-8.0-pipeline/12/

higher version is not tested because we have no 8+ branches in our repo

2018-09-20 07:48 UTC, laurynas-biveinis approved these changes

2018-09-20 07:51 UTC, laurynas-biveinis approved these changes

2018-09-20 07:54 UTC, merged