JEN-908-8.0
Percona-Lab/ps-build pull request #59
Opened 2018-09-21 06:57 UTC by abychko

centos-6: cannot find -lubsan
[*] installed devtoolset 7 for centos 6&7
[-] removed older compilers (devtoolset-2, devtoolset-6) from installation

2018-09-21 07:51 UTC, laurynas-biveinis requested changes
My idea was that in case of regular non-sanitizer build centos should use the same compilers as packagers do

2018-09-21 07:52 UTC, abychko commented
@EvgeniyPatlan answered in ticket that he is using devtoolset-7 for 8.0

2018-09-21 07:55 UTC, laurynas-biveinis commented
For both centos 6 and 7?

2018-09-21 07:55 UTC, abychko commented
yes

2018-09-21 07:56 UTC, laurynas-biveinis commented
Ah, ok then

2018-09-21 07:57 UTC, laurynas-biveinis requested changes

2018-09-21 07:57 UTC, laurynas-biveinis commented on docker/install-deps
> +# packages for ASAN and UBSAN builds
Outdated comment

2018-09-24 04:43 UTC, abychko commented
fixed

2018-09-24 10:35 UTC, laurynas-biveinis approved these changes
OK if testing OK

2018-09-24 11:20 UTC, abychko commented
https://ps.cd.percona.com/view/8.0/job/test-percona-server-8.0-pipeline/13/console

2018-09-24 11:20 UTC, merged