JEN-927 8.0
Percona-Lab/ps-build pull request #65
Opened 2018-10-09 05:56 UTC by abychko

merge 3 awk calls in local/test-binary
[+] added separate function to process .output files

2018-10-09 06:54 UTC, laurynas-biveinis reviewed
Looks good in general, minor comments, and needs evidence of testing. Please also change lower versions as applicable

2018-10-09 06:54 UTC, laurynas-biveinis commented on local/test-binary
> +    process_mtr_output MySQL ${WORKDIR_ABS}/mtr.output $WORKDIR_ABS/junit.xml
Do args need quoting in case there are spaces in them?

2018-10-09 06:54 UTC, laurynas-biveinis commented on local/test-binary
> +    process_mtr_output "Percona Server - TokuDB HotBackup" ${WORKDIR_ABS}/tokudb_hotbackup.output ${WORKDIR_ABS}/junit_tokudb_hotbackup.xml
Do args need quoting in case there are spaces in them?

2018-10-09 06:54 UTC, laurynas-biveinis commented on local/test-binary
> +    process_mtr_output "Percona Server - TokuDB" ${WORKDIR_ABS}/tokudb.output ${WORKDIR_ABS}/junit_tokudb.xml
Do args need quoting in case there are spaces in them?

2018-10-09 07:26 UTC, abychko commented on local/test-binary
> +    process_mtr_output MySQL ${WORKDIR_ABS}/mtr.output $WORKDIR_ABS/junit.xml
yes, positional arguments will be split by whitespaces, so "bla bla bla" without quotes will be parsed as 3 arguments, not one

2018-10-09 07:26 UTC, abychko commented on local/test-binary
> +    process_mtr_output "Percona Server - TokuDB HotBackup" ${WORKDIR_ABS}/tokudb_hotbackup.output ${WORKDIR_ABS}/junit_tokudb_hotbackup.xml
yes, positional arguments will be split by whitespaces, so "bla bla bla" without quotes will be parsed as 3 arguments, not one

2018-10-09 07:26 UTC, abychko commented on local/test-binary
> +    process_mtr_output "Percona Server - TokuDB" ${WORKDIR_ABS}/tokudb.output ${WORKDIR_ABS}/junit_tokudb.xml
yes, positional arguments will be split by whitespaces, so "bla bla bla" without quotes will be parsed as 3 arguments, not one

2018-10-09 08:45 UTC, abychko commented
test run succeeded https://ps.cd.percona.com/view/8.0/job/test-percona-server-8.0-pipeline/21/

2018-10-10 09:59 UTC, laurynas-biveinis requested changes

2018-10-10 09:59 UTC, laurynas-biveinis commented on local/test-binary
> +    process_mtr_output MySQL ${WORKDIR_ABS}/mtr.output $WORKDIR_ABS/junit.xml
So it's better to add quotes here, right?

2018-10-10 10:00 UTC, abychko commented
word `MySQL` doesn't contain whitespaces :)
so, it's not required

2018-10-10 10:02 UTC, laurynas-biveinis commented
> word `MySQL` doesn't contain whitespaces :)
> so, it's not required

I am referring to $WORKDIR_ABS in the 2nd and 3rd arg, which currently does not have spaces as it would already fail, but why not make it bulletproof, e.g. for local script testing?

2018-10-10 10:12 UTC, abychko commented
yes, you're right.

> bash-4.4$ ./z "Percona Server - TokuDB" "${WORKDIR_ABS}"/tokudb.output "${WORKDIR_ABS}"/junit_tokudb.xml
> Percona Server - TokuDB
> /Users/abychko/tmp/one two three/tokudb.output
> /Users/abychko/tmp/one two three/junit_tokudb.xml

2018-10-10 11:17 UTC, laurynas-biveinis commented on local/test-binary
> +    process_mtr_output MySQL "${WORKDIR_ABS}"/mtr.output "${WORKDIR_ABS}"/junit.xml
I'd quote entire args, but it's a stylistic point only

2018-10-10 11:17 UTC, laurynas-biveinis approved these changes

2018-10-10 11:17 UTC, merged