JEN-958
Percona-Lab/ps-build pull request #75
Opened 2018-11-15 17:19 UTC by abychko

8.0: switch to -DWITH_SYSTEM=libs
[-] deleted every occurence of WITH_SSL from Jenkins GUI and pipeline
[-] replaced WITH_SSL with WITH_SYSTEM=libs in build scripts

2018-11-15 17:19 UTC, abychko commented
I will post test results here when ready

2018-11-16 07:08 UTC, laurynas-biveinis reviewed
The script changes look OK, but this does need testing, in order to check what missing libs have to be installed

2018-11-27 11:07 UTC, abychko commented
test ran: https://ps2.cd.percona.com/view/TEST/job/test-percona-server-8.0-pipeline/3/console

2018-11-28 16:22 UTC, laurynas-biveinis requested changes

2018-11-28 16:22 UTC, laurynas-biveinis commented on local/build-binary
> +        -DWITH_SYSTEM=libs \
It's actually -DWITH_SYSTEM_LIBS=ON https://dev.mysql.com/doc/refman/8.0/en/source-configuration-options.html#option_cmake_with_system_libs

2018-11-29 08:28 UTC, abychko commented on local/build-binary
> +        -DWITH_SYSTEM=libs \
deleted

2018-11-29 08:42 UTC, abychko commented
new test run https://ps2.cd.percona.com/view/TEST/job/test-percona-server-8.0-pipeline/4/console

2018-11-29 08:58 UTC, laurynas-biveinis commented
Please provide link to the whole job, once it completes

2018-11-29 09:08 UTC, abychko commented
ok, will run whole matrix. makes sense, sorry

2018-12-06 07:45 UTC, abychko commented
started matrix https://ps2.cd.percona.com/view/8.0/job/percona-server-8.0-valgrind-param/

2018-12-06 09:05 UTC, laurynas-biveinis commented
@abychko please use 3637583bb5217f8e2a287870775fd5657de271bc, not HEAD, for any 8.0-testing jobs

2018-12-13 08:49 UTC, laurynas-biveinis commented
If testing needs to be run now, ok to use HEAD

2018-12-18 07:29 UTC, abychko commented
started https://ps2.cd.percona.com/job/percona-server-8.0-valgrind-param/4/

2018-12-18 08:51 UTC, closed without merging